### PR TITLE
M5Stack Core2's fixes, partial TouchPanel support  (part 1) , initialization of external I2C PortA, TO-DOs    

### PR DESCRIPTION
**Pull request by jcabad100**
M5Stack Core2's public static partial class M5Core2 PARTIAL initialization fixes and TO-DOs:

## Description

- There are bugs and missing stuff, the proposed changes are just the starting point to fix them all: 
- The Core2 external I2C port A  as documented in https://docs.m5stack.com/en/core/core2 uses GPIO 32 and 33 
- additionally GPIO 39 is used as INT output from Touch panel chip FT6336   
- Check TO-DO remarks for things to do next.
- I commented out old code that must be disabled i.e. wrongly assigned GPIO pins 

## Motivation and Context
- I am trying to help solving the current missing stuff on M5 Stack Core2
- The first issue would allow to use/attach external I2C devices on PortA because the first I2C bus is used internally only
- The second issue is the starting point to add support for Core2 Touch Panel 
- The proposed changes could not be tested nor completely solve the problems at hand; i hope it will help the next contributor
complete all the necessary tasks (See //TO-DO comments)

- Fixes/Closes/Resolves nanoFramework/Home#NNNN

## How Has This Been Tested?
- As i said, i have NOT being able to test any of the proposed modifications

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.M5Stack?pullRequest=40) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.M5Stack?pullRequest=40) before we can accept your contribution.<br/><br/>:x: jcabad100 [sign now](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.M5Stack?pullRequest=40)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nanoFramework.M5Stack?pullRequest=40) it.</sub>

**Review by jcabad100 — COMMENTED** [review]
Some changes seems not have been applied.

**Comment by Ellerbach** [comment]
Thanks for the submission. What I propose is to implement properly the touch screen and have it added to the IoT.Device repository. This will be reusable. Like this, the touch is not really useful. If you want to raise an event, there is a different way to do it. Also, I'm quite sure that if the touch screen is not setup properly, interrupts won't be activated.
I found the datasheets for it, one is the register (an Excel file :-)). All seems quite ok and will require work but doesn't seem too long.

**Comment by jcabad100** [comment]
and what happened with this old PR?

**Comment by josesimoes** [comment]
> and what happened with this old PR?

It's here... not sure exactly what you wanted to know about it...

**Comment by Ellerbach** [comment]
@jcabad100 closing this one as present in the latest changes.

**Pull request closed without merging**
