### PR TITLE
Update nanoFramework.System.IO.FileSystem  assembly reference for changed SDCard

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description

Update M5stack project to support latest **nanoFramework.System.IO.FileSystem** with SDCard updates.

## Motivation and Context
Build broken

## How Has This Been Tested?
Builds locally

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

## Summary by CodeRabbit

- **New Features**
	- Updated the `nanoFramework.System.IO.FileSystem` dependency version to `1.1.66` across multiple projects.

- **Bug Fixes**
	- Resolved issues related to the previous version of the `System.IO.FileSystem` dependency.

### CODE REVIEW

**Comment by networkfusion** [comment]
@AdrianSoundy , you probably need to update the `.nugetspec` file to match the updated:
``` Found in nuspec, but declared dependency version doesn't match!
expecting '1.1.66' but found '1.1.54'.```

**Comment by networkfusion** [comment]
@AdrianSoundy 
image

**Comment by AdrianSoundy** [comment]
@networkfusion 
Yes I saw that but the main problem now is the GitVersion also changed yesterday. Decided to update other PR first then can update this PR when branch updated

**Comment by networkfusion** [comment]
> @networkfusion Yes I saw that but the main problem now is the GitVersion also changed yesterday. Decided to update other PR first then can update this PR when branch updated

Oh, I hate when that happens.

**Comment by AdrianSoundy** [comment]
No need to complete this PR as another PR has resolved problem

**Pull request closed without merging**
